#pragma once

#define GUI_SUPPORT_CURSOR 1
#define GUI_SUPPORT_MOUSE  1
#define GUI_SUPPORT_TIMER  1

#define GUI_DEFAULT_FONT    &FontProp13_1
#define GUI_DEFAULT_CURSOR  &CursorArrowM
#define GUI_DEFAULT_BKCOLOR RGB_BLACK
#define GUI_DEFAULT_COLOR   RGB_WHITE
